### ISSUE TITLE
[Enhancement] Use a service to load iptables instead of rc.local

### ISSUE THREAD

**Issue by alex-ssom** [LeoRover/LeoOS#11]
Using a service configured the following way might improve the reliability of the iptables loading.

```bash
[Unit]
Description = Apply iptables rules
After=network-online.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'iptables-restore < /etc/iptables.ipv4.nat'

[Install]
WantedBy=multi-user.target
```

**Comment by bjsowa** [comment]
I think the `iptables-persistent` package from Ubuntu does exactly this. I might give it a try.

**Comment by alex-ssom** [comment]
I've had issues with the `iptables-persistent` package, hence the service solution but YMMV.

In short, the `iptables-persistent` loads the rules but instead of the expected behaviour of replacing the previous rules, it appended the saved rules.

**Comment by bjsowa** [comment]
I looked at the code of [iptables-persistent](https://salsa.debian.org/debian/iptables-persistent) and it seems to be doing [exactly what you proposed](https://salsa.debian.org/debian/iptables-persistent/-/blob/debian/plugins/15-ip4tables#L34). It has an additional config option for loading new rules without flushing the current ones but it is disabled by default.

It is included in the [newest release](https://github.com/LeoRover/LeoOS/releases/tag/1.0.0rc2).
