### ISSUE TITLE
Very small RAM size seen by the OS on 1.0.0rc1

### ISSUE THREAD

**Issue by alex-ssom** [LeoRover/LeoOS#13]
Hi, 

I'm testing the 1.0.0rc1 and I think I found an issue. The total RAM size seen by the OS doesn't match the hardware. The output of the following command is when running on a RPi4 4Gb.
```bash
$ free -h
              total        used        free      shared  buff/cache   available
Mem:          856Mi       488Mi       247Mi       1.0Mi       120Mi       304Mi
Swap:         428Mi        28Mi       399Mi

```

I'm guessing this might be why I'm having such trouble running the Autonomous Navigation example.

**Comment by bjsowa** [comment]
Did you change anything in `/boot/firmware/config.txt`? Could you show the contents of this file?

**Comment by alex-ssom** [comment]
I haven't modified it. Here it is just in case:

```bash
$ cat /boot/firmware/config.txt 
# https://www.raspberrypi.com/documentation/computers/config_txt.html

[pi4]
kernel=uboot_rpi_4.bin
max_framebuffers=2

[pi3]
kernel=uboot_rpi_3.bin

[all]
arm_64bit=1
device_tree_address=0x03000000

cmdline=cmdline.txt

start_x=1
gpu_mem=128

enable_uart=1
dtoverlay=vc4-fkms-v3d
dtoverlay=miniuart-bt
disable_overscan=1

# dtparam=i2c_arm=on,i2c_arm_baudrate=400000
# dtparam=spi=on
# dtparam=i2s=on
```

**Comment by alex-ssom** [comment]
Well, I found the issue. It turns out that I had a RPi4 1GB inside the rover 🤦‍♂️ Sorry for the unnecessary issue
