### ISSUE TITLE
disabling AP breaks ROS

### ISSUE THREAD

**Issue by Renslmf23** [LeoRover/LeoOS#14]
I don't want to connect via the AP but rather add the rover in my network. I want to use the external usb wifi card for the main connection, since it's way more powerful than the build-in wifi of the RPI. However, after running ap-disable and using nmtui to directly connect to my network, ROS fails to find master.localnet. It appears this is handled by a DNS-server and not the /etc/hosts file. Which DNS server does LeoOS use? Is there something else I can try to fix this? I'm using LeoOS 1.0.0rc1.

Edit: I get the following error message when doing anything ROS-related:
Unable to contact my own server at [xxxxxxx].
This usually means that the network is not configured properly.

**Comment by bjsowa** [comment]
When using your custom network configuration, you will need to properly set ROS environment variables in `/etc/ros/setup.bash` file.

As the ROS master is run on the robot you can leave:
```bash
export ROS_MASTER_URI=http://localhost:11311
```

The `ROS_HOSTNAME` and `ROS_IP` specify how the robot identifies to other computers on the ROS network. As you disabled the AP, you also disabled the DHCP/DNS server so the `master.localnet` address is no longer resolvable. To use an IP address instead, comment out the `export ROS_HOSTNAME` line and set ROS_IP:
```bash
# export ROS_HOSTNAME=master.localnet
export ROS_IP=X.X.X.X
```
where `X.X.X.X` is the IP address of the rover in your network.

Then, restart `leo` service
```
sudo systemctl restart leo
```

**Comment by bjsowa** [comment]
The default ROS network configuration has been changed in the latest release candidate:
https://github.com/LeoRover/LeoOS/blob/e4a3403141a010f61aeaaec6afacd5e051f7f152/stage3/03-leo-ros/files/setup.bash#L29-L30
Now to make ROS work after disabling AP, all you need to do is to change the ROS_IP variable.

There is not much I can do about it, as the ROS Master requires a resolvable IP address that it identifies with.

I'm closing this issue. If you have any idea how to fix this, leave a comment and I'll reopen the issue.
