### ISSUE TITLE
raspicam-node not set to manually installed

### ISSUE THREAD

**Issue by alex-ssom** [LeoRover/LeoOS#8]
I found out when I ran `apt autoremove` the camera stops working because the camera node isn't set to manually installed.

**Comment by bjsowa** [comment]
I was not able to reproduce this issue on LeoOS 0.2.2.
I tried upgrading all packages and then running `apt autoremove` but it did not remove any packages.

`apt show ros-melodic-raspicam-node` tells me that it is manually installed:
```
APT-Manual-Installed: yes
```

Are you able to provide steps for reproducing this issue?

**Comment by alex-ssom** [comment]
It's weird that you we're unable to reproduce that issue. I encountered it after flashing LeoOS 0.2.2 on the SD card.

**Comment by alex-ssom** [comment]
This bug isn't present in the new image https://github.com/LeoRover/LeoOS/releases/tag/1.0.0beta1
